apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: sample-mgo-rs-restore
  namespace: demo
  labels:
    app.kubernetes.io/name: mongodbs.kubedb.com
spec:
  task:
    name: mongodb-restore-v2020.12.17
  repository:
    name: gcs-repo-replicaset
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: restored-mgo-rs
  rules:
  - snapshots: [latest]
