/*
Copyright AppsCode Inc. and Contributors

Licensed under the PolyForm Noncommercial License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/PolyForm-Noncommercial-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stash.appscode.dev/mongodb/apis/installer/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *ImageRef) Reset()      { *m = ImageRef{} }
func (*ImageRef) ProtoMessage() {}
func (*ImageRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fbafe8100657908, []int{0}
}
func (m *ImageRef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ImageRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ImageRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageRef.Merge(m, src)
}
func (m *ImageRef) XXX_Size() int {
	return m.Size()
}
func (m *ImageRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageRef.DiscardUnknown(m)
}

var xxx_messageInfo_ImageRef proto.InternalMessageInfo

func (m *MongoDBBackup) Reset()      { *m = MongoDBBackup{} }
func (*MongoDBBackup) ProtoMessage() {}
func (*MongoDBBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fbafe8100657908, []int{1}
}
func (m *MongoDBBackup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MongoDBBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MongoDBBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MongoDBBackup.Merge(m, src)
}
func (m *MongoDBBackup) XXX_Size() int {
	return m.Size()
}
func (m *MongoDBBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_MongoDBBackup.DiscardUnknown(m)
}

var xxx_messageInfo_MongoDBBackup proto.InternalMessageInfo

func (m *MongoDBRestore) Reset()      { *m = MongoDBRestore{} }
func (*MongoDBRestore) ProtoMessage() {}
func (*MongoDBRestore) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fbafe8100657908, []int{2}
}
func (m *MongoDBRestore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MongoDBRestore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MongoDBRestore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MongoDBRestore.Merge(m, src)
}
func (m *MongoDBRestore) XXX_Size() int {
	return m.Size()
}
func (m *MongoDBRestore) XXX_DiscardUnknown() {
	xxx_messageInfo_MongoDBRestore.DiscardUnknown(m)
}

var xxx_messageInfo_MongoDBRestore proto.InternalMessageInfo

func (m *StashMongoDB) Reset()      { *m = StashMongoDB{} }
func (*StashMongoDB) ProtoMessage() {}
func (*StashMongoDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fbafe8100657908, []int{3}
}
func (m *StashMongoDB) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StashMongoDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StashMongoDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StashMongoDB.Merge(m, src)
}
func (m *StashMongoDB) XXX_Size() int {
	return m.Size()
}
func (m *StashMongoDB) XXX_DiscardUnknown() {
	xxx_messageInfo_StashMongoDB.DiscardUnknown(m)
}

var xxx_messageInfo_StashMongoDB proto.InternalMessageInfo

func (m *StashMongoDBList) Reset()      { *m = StashMongoDBList{} }
func (*StashMongoDBList) ProtoMessage() {}
func (*StashMongoDBList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fbafe8100657908, []int{4}
}
func (m *StashMongoDBList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StashMongoDBList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StashMongoDBList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StashMongoDBList.Merge(m, src)
}
func (m *StashMongoDBList) XXX_Size() int {
	return m.Size()
}
func (m *StashMongoDBList) XXX_DiscardUnknown() {
	xxx_messageInfo_StashMongoDBList.DiscardUnknown(m)
}

var xxx_messageInfo_StashMongoDBList proto.InternalMessageInfo

func (m *StashMongoDBSpec) Reset()      { *m = StashMongoDBSpec{} }
func (*StashMongoDBSpec) ProtoMessage() {}
func (*StashMongoDBSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fbafe8100657908, []int{5}
}
func (m *StashMongoDBSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StashMongoDBSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StashMongoDBSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StashMongoDBSpec.Merge(m, src)
}
func (m *StashMongoDBSpec) XXX_Size() int {
	return m.Size()
}
func (m *StashMongoDBSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_StashMongoDBSpec.DiscardUnknown(m)
}

var xxx_messageInfo_StashMongoDBSpec proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ImageRef)(nil), "stash.appscode.dev.mongodb.apis.installer.v1alpha1.ImageRef")
	proto.RegisterType((*MongoDBBackup)(nil), "stash.appscode.dev.mongodb.apis.installer.v1alpha1.MongoDBBackup")
	proto.RegisterType((*MongoDBRestore)(nil), "stash.appscode.dev.mongodb.apis.installer.v1alpha1.MongoDBRestore")
	proto.RegisterType((*StashMongoDB)(nil), "stash.appscode.dev.mongodb.apis.installer.v1alpha1.StashMongoDB")
	proto.RegisterType((*StashMongoDBList)(nil), "stash.appscode.dev.mongodb.apis.installer.v1alpha1.StashMongoDBList")
	proto.RegisterType((*StashMongoDBSpec)(nil), "stash.appscode.dev.mongodb.apis.installer.v1alpha1.StashMongoDBSpec")
}

func init() {
	proto.RegisterFile("stash.appscode.dev/mongodb/apis/installer/v1alpha1/generated.proto", fileDescriptor_1fbafe8100657908)
}

var fileDescriptor_1fbafe8100657908 = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcf, 0x6f, 0xd3, 0x3a,
	0x1c, 0x6f, 0xd6, 0x76, 0xeb, 0x73, 0xbb, 0xbe, 0xca, 0xef, 0xe9, 0x29, 0x9a, 0xf4, 0xb2, 0xaa,
	0xa7, 0x1e, 0xc0, 0xa1, 0x15, 0xa0, 0x1d, 0x10, 0x62, 0x61, 0x42, 0x9a, 0xc4, 0x98, 0xe4, 0x4d,
	0x42, 0x42, 0x1c, 0x70, 0x53, 0x37, 0x35, 0x6d, 0xe2, 0xc8, 0x76, 0x0a, 0xbd, 0x71, 0xe7, 0xc2,
	0x5f, 0x85, 0x76, 0xdc, 0x8d, 0x9d, 0x26, 0x56, 0xfe, 0x11, 0x14, 0xc7, 0x6d, 0xd3, 0x55, 0x88,
	0xb1, 0xdd, 0xe2, 0xef, 0xf7, 0xf3, 0xc3, 0x1f, 0xe7, 0xfb, 0x05, 0x9e, 0x54, 0x44, 0x0e, 0x11,
	0x89, 0x63, 0xe9, 0xf3, 0x3e, 0x45, 0x7d, 0x3a, 0x71, 0x43, 0x1e, 0x05, 0xbc, 0xdf, 0x73, 0x49,
	0xcc, 0xa4, 0xcb, 0x22, 0xa9, 0xc8, 0x78, 0x4c, 0x85, 0x3b, 0xe9, 0x90, 0x71, 0x3c, 0x24, 0x1d,
	0x37, 0xa0, 0x11, 0x15, 0x44, 0xd1, 0x3e, 0x8a, 0x05, 0x57, 0x1c, 0x76, 0xd7, 0x35, 0x90, 0xd1,
	0x40, 0xa9, 0x06, 0x5a, 0x68, 0xa0, 0xb9, 0xc6, 0xce, 0xfd, 0x80, 0xa9, 0x61, 0xd2, 0x43, 0x3e,
	0x0f, 0xdd, 0x80, 0x07, 0xdc, 0xd5, 0x52, 0xbd, 0x64, 0xa0, 0x4f, 0xfa, 0xa0, 0xbf, 0x32, 0x8b,
	0x9d, 0x87, 0xa3, 0x3d, 0x89, 0x18, 0x4f, 0xaf, 0x14, 0x12, 0x7f, 0xc8, 0x22, 0x2a, 0xa6, 0x6e,
	0x3c, 0x0a, 0xb2, 0x3b, 0x86, 0x54, 0x11, 0x77, 0xb2, 0x76, 0xb1, 0x1d, 0xf7, 0x57, 0x2c, 0x91,
	0x44, 0x8a, 0x85, 0x74, 0x8d, 0xf0, 0xf8, 0x77, 0x04, 0xe9, 0x0f, 0x69, 0x48, 0xae, 0xf3, 0x5a,
	0x9f, 0x2d, 0x50, 0x39, 0x0c, 0x49, 0x40, 0x31, 0x1d, 0xc0, 0x7b, 0xa0, 0x22, 0x68, 0xc0, 0xa4,
	0x12, 0x53, 0xdb, 0x6a, 0x5a, 0xed, 0xbf, 0xbc, 0xc6, 0xd9, 0xe5, 0x6e, 0x61, 0x76, 0xb9, 0x5b,
	0xc1, 0xa6, 0x8e, 0x17, 0x08, 0xd8, 0x05, 0x40, 0xd0, 0x98, 0x4b, 0xa6, 0xb8, 0x98, 0xda, 0x1b,
	0x1a, 0x0f, 0x0d, 0x1e, 0xe0, 0x45, 0x07, 0xe7, 0x50, 0xf0, 0x7f, 0x50, 0x54, 0x24, 0xb0, 0x8b,
	0x1a, 0x5c, 0x35, 0xe0, 0xe2, 0x29, 0x09, 0x70, 0x5a, 0x6f, 0x75, 0xc0, 0xf6, 0x51, 0xfa, 0xfc,
	0x07, 0x9e, 0x47, 0xfc, 0x51, 0x12, 0xc3, 0x26, 0x28, 0x11, 0x11, 0x48, 0x73, 0x9b, 0x9a, 0x21,
	0x94, 0xf6, 0x45, 0x20, 0xb1, 0xee, 0xb4, 0xba, 0xa0, 0x6e, 0x28, 0x98, 0x4a, 0xc5, 0x05, 0xbd,
	0x01, 0xe7, 0xc2, 0x02, 0xb5, 0x93, 0xf4, 0xcf, 0x1b, 0x26, 0x7c, 0x07, 0x2a, 0xe9, 0x9f, 0xe8,
	0x13, 0x45, 0x34, 0xad, 0xda, 0x7d, 0x80, 0xb2, 0x07, 0x45, 0xf9, 0x07, 0x45, 0xf1, 0x28, 0xc8,
	0xe6, 0x22, 0x45, 0xa3, 0x49, 0x07, 0x1d, 0xf7, 0xde, 0x53, 0x5f, 0x1d, 0x51, 0x45, 0x96, 0xd1,
	0x97, 0x35, 0xbc, 0x50, 0x85, 0x03, 0x50, 0x92, 0x31, 0xf5, 0xf5, 0x33, 0x55, 0xbb, 0x07, 0xe8,
	0xcf, 0x07, 0x0f, 0xe5, 0x6f, 0x7c, 0x12, 0x53, 0x7f, 0x19, 0x2d, 0x3d, 0x61, 0xad, 0xdf, 0xfa,
	0x66, 0x81, 0x46, 0x1e, 0xf8, 0x92, 0x49, 0x05, 0xdf, 0xae, 0xc5, 0x43, 0x37, 0x8b, 0x97, 0xb2,
	0x75, 0xb8, 0xc5, 0x1c, 0xcc, 0x2b, 0xb9, 0x68, 0x14, 0x94, 0x99, 0xa2, 0xa1, 0xb4, 0x37, 0x9a,
	0xc5, 0x76, 0xb5, 0xfb, 0xec, 0xae, 0xd9, 0xbc, 0x6d, 0x63, 0x56, 0x3e, 0x4c, 0x65, 0x71, 0xa6,
	0xde, 0xfa, 0x5a, 0x5a, 0x4d, 0x96, 0x86, 0x86, 0x7b, 0xa0, 0x16, 0x91, 0x90, 0x1e, 0x4f, 0xa8,
	0x10, 0xac, 0x4f, 0xcd, 0x3f, 0xff, 0xd7, 0x08, 0xd4, 0x5e, 0xe5, 0x7a, 0x78, 0x05, 0x09, 0x0f,
	0x40, 0x63, 0x90, 0x8c, 0xc7, 0x2b, 0xec, 0x6c, 0x86, 0x6d, 0xc3, 0x6e, 0xbc, 0xb8, 0xd6, 0xc7,
	0x6b, 0x0c, 0x48, 0x40, 0x99, 0xa5, 0xdb, 0xa3, 0x27, 0xba, 0xda, 0x7d, 0x72, 0x9b, 0xec, 0xf3,
	0xf5, 0xcb, 0xe5, 0xd6, 0x95, 0x4c, 0x19, 0x32, 0xb0, 0xd9, 0xd3, 0xcb, 0x60, 0x97, 0xb4, 0xc7,
	0xfe, 0x6d, 0x3c, 0x56, 0xb6, 0xca, 0xab, 0x1b, 0xa3, 0xcd, 0xec, 0x8c, 0x8d, 0x01, 0x0c, 0xc1,
	0x96, 0xc8, 0x96, 0xc8, 0x2e, 0x6b, 0x2f, 0xef, 0x0e, 0x5e, 0x66, 0x1d, 0xbd, 0xbf, 0x8d, 0xd9,
	0x96, 0x29, 0xe0, 0xb9, 0x07, 0x7c, 0x0a, 0xea, 0x21, 0xf9, 0xf8, 0x9c, 0x47, 0x7e, 0x22, 0x04,
	0x8d, 0xfc, 0xa9, 0xbd, 0xd9, 0xb4, 0xda, 0x65, 0xef, 0x3f, 0xc3, 0xa8, 0x1f, 0xad, 0x74, 0xf1,
	0x35, 0x34, 0x7c, 0x04, 0xaa, 0x1f, 0x08, 0x53, 0xa7, 0x2c, 0xa4, 0x3c, 0x51, 0xf6, 0x56, 0xd3,
	0x6a, 0x17, 0xbd, 0x7f, 0x0c, 0xb9, 0xfa, 0x7a, 0xd9, 0xc2, 0x79, 0x9c, 0x87, 0xce, 0xae, 0x9c,
	0xc2, 0xf9, 0x95, 0x53, 0xb8, 0xb8, 0x72, 0x0a, 0x9f, 0x66, 0x8e, 0x75, 0x36, 0x73, 0xac, 0xf3,
	0x99, 0x63, 0x5d, 0xcc, 0x1c, 0xeb, 0xfb, 0xcc, 0xb1, 0xbe, 0xfc, 0x70, 0x0a, 0x6f, 0x2a, 0xf3,
	0x3c, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x4a, 0xb7, 0xb0, 0x69, 0x06, 0x00, 0x00,
}

func (m *ImageRef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ImageRef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ImageRef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Tag)
	copy(dAtA[i:], m.Tag)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Tag)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Repository)
	copy(dAtA[i:], m.Repository)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Repository)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Registry)
	copy(dAtA[i:], m.Registry)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Registry)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MongoDBBackup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MongoDBBackup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MongoDBBackup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Args)
	copy(dAtA[i:], m.Args)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Args)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MongoDBRestore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MongoDBRestore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MongoDBRestore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Args)
	copy(dAtA[i:], m.Args)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Args)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *StashMongoDB) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StashMongoDB) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StashMongoDB) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *StashMongoDBList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StashMongoDBList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StashMongoDBList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *StashMongoDBSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StashMongoDBSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StashMongoDBSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.WaitTimeout))
	i--
	dAtA[i] = 0x38
	i = encodeVarintGenerated(dAtA, i, uint64(m.MaxConcurrency))
	i--
	dAtA[i] = 0x30
	{
		size, err := m.Restore.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Backup.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Image.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	i -= len(m.FullnameOverride)
	copy(dAtA[i:], m.FullnameOverride)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.FullnameOverride)))
	i--
	dAtA[i] = 0x12
	i -= len(m.NameOverride)
	copy(dAtA[i:], m.NameOverride)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.NameOverride)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ImageRef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Registry)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Repository)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Tag)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *MongoDBBackup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Args)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *MongoDBRestore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Args)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *StashMongoDB) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *StashMongoDBList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *StashMongoDBSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NameOverride)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.FullnameOverride)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Image.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Backup.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Restore.Size()
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.MaxConcurrency))
	n += 1 + sovGenerated(uint64(m.WaitTimeout))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ImageRef) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ImageRef{`,
		`Registry:` + fmt.Sprintf("%v", this.Registry) + `,`,
		`Repository:` + fmt.Sprintf("%v", this.Repository) + `,`,
		`Tag:` + fmt.Sprintf("%v", this.Tag) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MongoDBBackup) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MongoDBBackup{`,
		`Args:` + fmt.Sprintf("%v", this.Args) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MongoDBRestore) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MongoDBRestore{`,
		`Args:` + fmt.Sprintf("%v", this.Args) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StashMongoDB) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StashMongoDB{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "StashMongoDBSpec", "StashMongoDBSpec", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StashMongoDBList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]StashMongoDB{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "StashMongoDB", "StashMongoDB", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&StashMongoDBList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *StashMongoDBSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StashMongoDBSpec{`,
		`NameOverride:` + fmt.Sprintf("%v", this.NameOverride) + `,`,
		`FullnameOverride:` + fmt.Sprintf("%v", this.FullnameOverride) + `,`,
		`Image:` + strings.Replace(strings.Replace(this.Image.String(), "ImageRef", "ImageRef", 1), `&`, ``, 1) + `,`,
		`Backup:` + strings.Replace(strings.Replace(this.Backup.String(), "MongoDBBackup", "MongoDBBackup", 1), `&`, ``, 1) + `,`,
		`Restore:` + strings.Replace(strings.Replace(this.Restore.String(), "MongoDBRestore", "MongoDBRestore", 1), `&`, ``, 1) + `,`,
		`MaxConcurrency:` + fmt.Sprintf("%v", this.MaxConcurrency) + `,`,
		`WaitTimeout:` + fmt.Sprintf("%v", this.WaitTimeout) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ImageRef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ImageRef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ImageRef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registry", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registry = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repository", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repository = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MongoDBBackup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MongoDBBackup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MongoDBBackup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MongoDBRestore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MongoDBRestore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MongoDBRestore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StashMongoDB) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StashMongoDB: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StashMongoDB: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StashMongoDBList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StashMongoDBList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StashMongoDBList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, StashMongoDB{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StashMongoDBSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StashMongoDBSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StashMongoDBSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NameOverride", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NameOverride = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullnameOverride", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FullnameOverride = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Image.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Backup", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Backup.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Restore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Restore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxConcurrency", wireType)
			}
			m.MaxConcurrency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxConcurrency |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WaitTimeout", wireType)
			}
			m.WaitTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WaitTimeout |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
