apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: sample-mongodb
  namespace: demo
spec:
  version: "3.4.22"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
