apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: sample-mgo-rs
  namespace: demo
spec:
  version: "3.6.13"
  replicas: 3
  replicaSet:
    name: rs0
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
