apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: sample-mgo-rs-ssl
  namespace: demo
spec:
  version: "3.6-v4"
  replicas: 3
  replicaSet:
    name: rs0
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
  clusterAuthMode: x509
  sslMode: requireSSL
