apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: restored-mgo-sh
  namespace: demo
spec:
  databaseSecret:
    secretName: sample-mgo-sh-auth
  version: 4.0.3
  shardTopology:
    configServer:
      replicas: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      replicas: 2
      strategy:
        type: RollingUpdate
    shard:
      replicas: 3
      shards: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
  init:
    stashRestoreSession:
      name: sample-mgo-sh-restore
  terminationPolicy: WipeOut
  clusterAuthMode: x509
  sslMode: requireSSL
